# Dependencies
markdown:         kramdown
highlighter:      rouge

gems:             [jekyll-gist, jekyll-sitemap]

permalink:        pretty

# Setup
title:            WWW
description:      'World Wide Wiki'
baseurl:          

asset_url:        https://rimeofficial.github.io/static

# Custom vars
version:          1.0.0

# Github vars
github:
  username:       rimeofficial

collections:
  docs:
    output:       true
    permalink:    /:path/

defaults:
  - scope:
      path:       ''
      type:       docs
    values:
      layout:     page

ga:               UA-41643154-1

app:
  name:           Rime
  domain:         rime.co