# Dependencies
# markdown:         redcarpet
markdown:         kramdown
# highlighter:      pygments
highlighter:      rouge

gems:             [jekyll-paginate, jekyll-gist]

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            WWW
tagline:          'World Wide Web'
description:      'Connecting Worlds Information'
url:              http://www.rime.co
baseurl:          

author:
  name:           'Rime'
  url:            https://rime.co

paginate:         5
# paginate_path:    'page:num'

# Custom vars
version:          1.0.0

github:
  repo:           https://GitHub.com/RimeOfficial
